### ISSUE TITLE
There is an error in my app | jsx-control-statements .

### ISSUE THREAD

**Issue by xywenke** [nkbt/esnext-quickstart#10]
When i try to use jsx-control-statements(v1.1.2) in my application, it says "Module build failed: TypeError: babel.Transformer is not a function" , my babel is v6.0.1 and I write my webpack.config.js like this : 
{test: /.js$/, loaders: ['react-hot', 'babel-loader?presets[]=es2015&plugins=jsx-control-statements/babel'], exclude: /node_modules/} .

Maybe you can help me . thank you !

**Comment by nkbt** [comment]
Answered in #9
