### ISSUE TITLE
There is an error in my app.

### ISSUE THREAD

**Issue by xywenke** [nkbt/esnext-quickstart#9]
When I use jsx-control-statements in my application it says "Module build  failed:TypeError:babel.Transformer is not a function".
my babel-loader is v6.0.1 , and I write config in my webpack.config.js like this: {test: /.js$/, loaders: ['react-hot', 'babel-loader?presets[]=es2015&plugins=jsx-control-statements/babel'], exclude: /node_modules/} .
I need your help, thank you !

**Comment by nkbt** [comment]
As far as I know, jsx-control-statements are implemented via separate babel plugin, they use `"babel": "^5.8.23",` which is incompatible with babel6.

On a side note, I strongly discourage anyone from using jsx-control-statements and similar to them packages for multiple reasons. Like hard to debug, support, lack of transparency  and clarity, etc. JSX is a functional composition and if you do not import your function and they just magically appear, that really smells and reminds of global variables usage.
